ExternalPortal/ViewModels/CheckAnswersViewModel.cs
using ExternalPortal.Enums;
using System;
using System.Collections.Generic;

namespace ExternalPortal.ViewModels
{
    public class CheckAnswersViewModel
    {
        public Guid OrganisationId { get; set; }
        public TaskType TaskType { get; set; }
        public string BackAction { get; set; }
        public List<Answer> Answers { get; set; }

        public CheckAnswersViewModel(TaskType taskType)
        {
            this.TaskType = taskType;
            this.Answers = new List<Answer>();
        }
    }

    public struct Answer
    {
        public TaskPropertyName PropertyName { get; set; }
        public string PropertyValue { get; set; }
        public string ChangeLink { get; set; }
    }
}

ExternalPortal/ViewModels/PlantLocation.cs
using GovUkDesignSystem.Attributes;

namespace Ofgem.API.GGSS.DomainModels
{
    public enum PlantLocation
    {
        [GovUkRadioCheckboxLabelText(Text = "England")]
        England,

        [GovUkRadioCheckboxLabelText(Text = "Scotland")]
        Scotland,

        [GovUkRadioCheckboxLabelText(Text = "Wales")]
        Wales
    }
}

ExternalPortal/ViewModels/ProductionDetails/ProductionDetailsStartDateViewModel.cs
using System;
using GovUkDesignSystem.Attributes.DataBinding;
using GovUkDesignSystem.Attributes.ValidationAttributes;
using GovUkDesignSystem.ModelBinders;
using Microsoft.AspNetCore.Mvc;

namespace ExternalPortal.ViewModels.ProductionDetails
{
    public class ProductionDetailsStartDateViewModel
    {
        [ModelBinder(typeof(GovUkMandatoryDateBinder))]
        [GovUkValidateRequired(ErrorMessageIfMissing = "Enter date of injection")]
        [GovUkDataBindingDateErrorText("Date of injection", "date of injection")]
        public DateTime? StartDate { get; set; }
    }
}

ExternalPortal/ViewModels/Shared/ConfirmationViewModel.cs
using ExternalPortal.ViewModels.Shared.Layouts;

namespace ExternalPortal.ViewModels.Shared
{
    public class ConfirmationViewModel : SimplePageHeaderLayoutViewModel
    {

    }
}

ExternalPortal/Controllers/StageOneController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExternalPortal.Constants;
using ExternalPortal.Extensions;
using ExternalPortal.Helpers;
using ExternalPortal.Models;
using ExternalPortal.Services;
using ExternalPortal.ViewModels;
using ExternalPortal.ViewModels.Shared;
using ExternalPortal.ViewModels.Shared.Components;
using ExternalPortal.ViewModels.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Ofgem.API.GGSS.Domain.ModelValues;
using Ofgem.API.GGSS.DomainModels;
using Ofgem.GovUK.Notify.Client;
using InstallationModel = ExternalPortal.ViewModels.InstallationModel;
using TaskStatus = ExternalPortal.Enums.TaskStatus;

namespace ExternalPortal.Controllers
{
    public class StageOneController : BaseController
    {
        private readonly ILogger<StageOneController> _logger;
        private readonly ISaveDocumentService _saveDocumentService;
        private readonly IGetApplicationService _getApplicationService;
        private readonly IUpdateApplicationService _updateApplicationService;
        private readonly ISendEmailService _sendEmailService;
        private readonly IOptions<SendEmailConfig> _sendEmailConfig;

        public StageOneController(
            IRedisCacheService redisCache,
            ILogger<StageOneController> logger,
            ISaveDocumentService saveDocumentService,
            IGetApplicationService getApplicationService,
            IUpdateApplicationService updateApplicationService,
            ISendEmailService sendEmailService,
            IOptions<SendEmailConfig> sendEmailConfig
            ) : base(redisCache)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _saveDocumentService = saveDocumentService;
            _getApplicationService = getApplicationService;
            _updateApplicationService = updateApplicationService;
            _sendEmailService = sendEmailService;
            _sendEmailConfig = sendEmailConfig;
        }

        [HttpGet]
        [Route(UrlKeys.PlantLocationLink)]
        public async Task<IActionResult> PlantLocation(CancellationToken token)
        {
            _logger.LogDebug("PlantLocation action on StageOneController controller called");

            var persistedApplication = await RetrieveCurrentApplicationFromApi();

            var model = new PlantDetailsModel
            {
                BackAction = UrlKeys.PlantDetailsWhatYouWillNeedLink,
                ReferenceParams = new Dictionary<string, string>()
                {
                    { UrlKeys.ReturnToYourApplicationLink, "/task-list" }
                },
                ReturnUrl = HttpContext.Request.Query["returnUrl"],
                Location = (persistedApplication.StageOne.TellUsAboutYourSite.PlantLocation == null ? Ofgem.API.GGSS.DomainModels.PlantLocation.England : Enum.Parse<PlantLocation>(persistedApplication.StageOne.TellUsAboutYourSite.PlantLocation))
            };

            return View(nameof(PlantLocation), model);
        }

        [HttpPost]
        public async Task<IActionResult> PlantLocation([FromForm] PlantDetailsModel viewModel)
        {
            var model = new PlantDetailsModel();

            if (ModelState.GetFieldValidationState(nameof(viewModel.Location)) == ModelValidationState.Invalid)
            {
                return View(nameof(PlantLocation), model);
            }

            var persistedApplication = await RetrieveCurrentApplicationFromApi();

            var currentTask = persistedApplication.StageOne.TellUsAboutYourSite;
            if (currentTask.Status == TaskStatus.NotStarted.ToString())
            {
                currentTask.Status = TaskStatus.InProgress.ToString();
            }

            currentTask.PlantLocation = viewModel.Location.ToString();
            await PersistApplicationToApi(persistedApplication);

            if (!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return RedirectToAction(nameof(CheckAnswers));
            }
            
            return RedirectToAction(nameof(LatLongAnaerobic));
        }
        
        [HttpGet]
        [Route(UrlKeys.LatLongAnaerobicLink)]
        public async Task<IActionResult> LatLongAnaerobic()
        {
            _logger.LogDebug("LatLongAnaerobic action on StageOneController controller called");

            var persistedApplication = await RetrieveCurrentApplicationFromApi();

            var persistedLatLong = persistedApplication.StageOne.TellUsAboutYourSite.LatitudeLongitudeAnaerobic;

            var model = new LatitudeLongitudeModel()
            {
                LatitudeLongitudeAnaerobic = new LatitudeLongitudeValue()
                {
                    Latitude = persistedLatLong.Latitude == 0 ? (double?)null : persistedLatLong.Latitude,
                    Longitude = persistedLatLong.Longitude == 0 ? (double?)null : persistedLatLong.Longitude
                },
                ReturnUrl = HttpContext.Request.Query["returnUrl"]
            };

            return View(nameof(LatLongAnaerobic), model);
        }
        
        [HttpPost]
        [Route(UrlKeys.LatLongAnaerobicLink)]
        public async Task<IActionResult> LatLongAnaerobic([FromForm] LatitudeLongitudeModel viewModel)
        {

            if (!ModelState.IsValid)
            {
                return View(nameof(LatLongAnaerobic), viewModel);
            }
            
            var persistedApplication = await RetrieveCurrentApplicationFromApi();

            var currentTask = persistedApplication.StageOne.TellUsAboutYourSite;
            if (currentTask.Status == TaskStatus.NotStarted.ToString())
            {
                currentTask.Status = TaskStatus.InProgress.ToString();
            }

            if (viewModel.LatitudeLongitudeAnaerobic?.Latitude != null)
            {
                currentTask.LatitudeLongitudeAnaerobic.Latitude = viewModel.LatitudeLongitudeAnaerobic.Latitude.Value;
            }

            if (viewModel.LatitudeLongitudeAnaerobic?.Longitude != null)
            {
                currentTask.LatitudeLongitudeAnaerobic.Longitude = viewModel.LatitudeLongitudeAnaerobic.Longitude.Value;
            }

            await PersistApplicationToApi(persistedApplication);
            
            if (!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return RedirectToAction(nameof(CheckAnswers));
            }

            return RedirectToAction(nameof(LatLongInjection));
        }
        
        [HttpGet]
        [Route(UrlKeys.LatLongInjectionLink)]
        public async Task<IActionResult> LatLongInjection()
        {
            _logger.LogDebug("LatLongInjection action on StageOneController controller called");
        
            var persistedApplication = await RetrieveCurrentApplicationFromApi();
            
            var persistedLatLong = persistedApplication.StageOne.TellUsAboutYourSite.LatitudeLongitudeInjection;

            var model = new LatitudeLongitudeModel()
            {
                LatitudeLongitudeInjection = new LatitudeLongitudeValue()
                {
                    Latitude = persistedLatLong.Latitude == 0 ? (double?)null : persistedLatLong.Latitude,
                    Longitude = persistedLatLong.Longitude == 0 ? (double?)null : persistedLatLong.Longitude
                },
                ReturnUrl = HttpContext.Request.Query["returnUrl"]
            };

            return View(nameof(LatLongInjection), model);
        }
        
        [HttpPost]
        [Route(UrlKeys.LatLongInjectionLink)]
        public async Task<IActionResult> LatLongInjection([FromForm] LatitudeLongitudeModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(LatLongInjection), viewModel);
            }
            
            var persistedApplication = await RetrieveCurrentApplicationFromApi();
        
            var currentTask = persistedApplication.StageOne.TellUsAboutYourSite;
            if (currentTask.Status == TaskStatus.NotStarted.ToString())
            {
                currentTask.Status = TaskStatus.InProgress.ToString();
            }
        
            if (viewModel.LatitudeLongitudeInjection.Latitude != null)
            {
                currentTask.LatitudeLongitudeInjection.Latitude = viewModel.LatitudeLongitudeInjection.Latitude.Value;
            }
            
            if (viewModel.LatitudeLongitudeInjection.Longitude != null)
            {
                currentTask.LatitudeLongitudeInjection.Longitude = viewModel.LatitudeLongitudeInjection.Longitude.Value;
            }
            await PersistApplicationToApi(persistedApplication);
            
            if (!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return RedirectToAction(nameof(CheckAnswers));
            }
        
            return RedirectToAction(nameof(HasPostcode));
        }

        [HttpGet]
        [Route(UrlKeys.CapacityUploadLink)]
        public async Task<IActionResult> CapacityUpload(PlantDetailsModel viewModel = null)
        {
            var persistedApplication = await RetrieveCurrentApplicationFromApi();

            var model = new PlantDetailsModel
            {
                BackAction = UrlKeys.PlantLocationLink,
                ReferenceParams = new Dictionary<string, string>()
                {
                    { UrlKeys.ReturnToYourApplicationLink, "/task-list" }
                },
                CapacityCheckDocument = persistedApplication.StageOne.TellUsAboutYourSite.CapacityCheckDocument,
                ReturnUrl = viewModel.ReturnUrl
            };

            return View(nameof(CapacityUpload), model);
        }

        [HttpPost]

ExternalPortal/Views/StageOne/CapacityUpload.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.PlantDetailsModel

@{
    ViewData["Title"] = "Stage One - Capacity Upload";

    @if (Model.BackLink != null)
    {
        <p><a href="javascript:history.go(-1)" class="govuk-back-link">Back</a></p>
    }
}

@{
    var formError = Model.HasError() ? "govuk-form-group--error" : "";
}

<form action="/stage-one/capacity-upload" method="post" enctype="multipart/form-data">
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <fieldset class="govuk-fieldset">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                    <h1 class="govuk-fieldset__heading">
                        Upload your connection agreement
                    </h1>
                </legend>

                <div id="more-detail-hint" class="govuk-hint">
                    <p class="govuk-body">This will give us an early indication that the gas network can accept the volume of biomethane you plan to inject, flow rate and capacity.</p>
                    <p class="govuk-body">This document must be signed and show the injection points you discussed with the network.</p>
                    <p class="govuk-body">You can only upload PDF, JPG, PNG, BMP, TIF, XLS or XLSX files. No file can be larger than 5MB.</p>
                </div>
            </fieldset>

            <div class="govuk-form-group @formError">
                @{
                    if (Model.HasError())
                    {
                        <span id="transport-upload-error" class="govuk-error-message">
                            @Model.Error
                        </span>
                    }
                }
                <label class="govuk-label" for="file">
                    Upload a file
                </label>
                <input class="govuk-file-upload" id="file" name="file" type="file">
            </div>
            <div class="govuk-button-group">
                @await Html.GovUkButton(new ButtonViewModel
                {
                    Text = "Save and continue",
                    Type = "Submit"
                })
            </div>
            @if (Model.BackLink != null)
            {
                await Html.RenderPartialAsync("Components/ReturnToYourApplication", Model.BackLink);
            }
        </div>
    </div>
    @Html.HiddenFor(m => m.ReturnUrl)
</form>

ExternalPortal/Views/StageOne/CapacityUploadConfirm.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents
@model ExternalPortal.ViewModels.PlantDetailsModel

@{
    ViewData["Title"] = "Check your gas network capacity document upload - Tell us about your site - Green Gas Support Scheme";

    var formError = Model.HasError() ? "govuk-form-group--error" : "";

    await Html.RenderPartialAsync("Components/ViewBackLink");
}

@using (Html.BeginForm("CapacityUploadConfirm", "StageOne", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                <h1 class="govuk-fieldset__heading">
                    Check your connection agreement document upload
                </h1>
            </legend>

            @{
                await Html.RenderPartialAsync("Components/UploadFileDetails",
                    new ViewDataDictionary(ViewData)
                    {
                        { "Id", Model.CapacityCheckDocument.FileId },
                        { "Name", Model.CapacityCheckDocument.FileName },
                        { "Size", Model.CapacityCheckDocument.FileSizeAsString },
            });
            }

            <div class="govuk-form-group @formError">
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
                        Is this file correct?
                    </legend>
                    @{
                        if (Model.HasError())
                        {
                            <span id="transport-upload-error" class="govuk-error-message">
                                @Model.Error
                            </span>
                        }
                    }
                    <div class="govuk-radios">
                        <div class="govuk-radios__item">
                            <input class="govuk-radios__input" id="documentAgree-yes" name="documentAgree" type="radio" value="Yes">
                            <label class="govuk-label govuk-radios__label" for="documentAgree-yes">
                                Yes, add this file
                            </label>
                        </div>
                        <div class="govuk-radios__item">
                            <input class="govuk-radios__input" id="documentAgree-no" name="documentAgree" type="radio" value="No">
                            <label class="govuk-label govuk-radios__label" for="documentAgree-no">
                                No, I want to upload a different file
                            </label>
                        </div>

                    </div>
                    @Html.HiddenFor(m => m.ReturnUrl)
                </fieldset>
            </div>
            <p>
                <div class="govuk-button-group">
                    @await Html.GovUkButton(new ButtonViewModel
                    {
                        Text = "Save and continue",
                                Type = "submit"
                    })
                </div>
                @if (Model.BackLink != null)
                {
                    await Html.RenderPartialAsync("Components/ReturnToYourApplication", Model.BackLink);
                }
            </p>
        </div>
    </div>
}

ExternalPortal/Views/StageOne/CheckAnswers.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents
@model StageOneModel
@{
    ViewData["Title"] = "Stage One - Feedstock Supply";
}
<form action="check-answers" method="post" novalidate>
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds-from-desktop">

            <h1 class="govuk-heading-l">Check your answers before sending your application</h1>

            <h2 class="govuk-heading-m">Plant details</h2>

            <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Location
                </dt>
                <dd class="govuk-summary-list__value">
                    @Model.PlantLocation
                </dd>
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="plant-location">
                        Change<span class="govuk-visually-hidden"> plant location</span>
                    </a>
                </dd>
               </div>

                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Connection agreement
                    </dt>
                    <dd class="govuk-summary-list__value">
                        @Model.CapacityUploadFileName
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        <a class="govuk-link" href="capacity-upload">
                            Change<span class="govuk-visually-hidden"> connection agreement</span>
                        </a>
                    </dd>
                </div>

                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Plant name
                    </dt>
                    <dd class="govuk-summary-list__value">
                        @Model.PlantAddress.Name
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        <a class="govuk-link" href="plant-address">
                            Change<span class="govuk-visually-hidden"> plant name</span>
                        </a>
                    </dd>
                </div>

                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key">
                        Site address
                    </dt>
                    <dd class="govuk-summary-list__value">
                        <p class="govuk-body">@Model.PlantAddress.Line1</p>
                        <p class="govuk-body">@Model.PlantAddress.Line2</p>
                        <p class="govuk-body">@Model.PlantAddress.Town</p>
                        <p class="govuk-body">@Model.PlantAddress.County</p>
                        <p class="govuk-body">@Model.PlantAddress.Postcode</p>
                    </dd>
                    <dd class="govuk-summary-list__actions">
                        <a class="govuk-link" href="plant-address">
                            Change<span class="govuk-visually-hidden"> site address</span>
                        </a>
                    </dd>
                </div>
            </dl>

        <h2 class="govuk-heading-m">Planning permission</h2>

        <dl class="govuk-summary-list govuk-!-margin-bottom-9">
            <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Planning outcome
            </dt>
            @if (Model.HasPlanningPermission)
            {
                <dd class="govuk-summary-list__value">
                    I was given planning permission
                </dd>
            }
            else
            {
                <dd class="govuk-summary-list__value">
                    Planning permission not required
                </dd>
            }
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="planning-permission">
                    Change<span class="govuk-visually-hidden"> planning outcome</span>
                </a>
            </dd>
            </div>
    @if (Model.HasPlanningPermission)
    {
        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Planning upload
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.PlanningPermissionFileName
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="planning-upload">
                    Change<span class="govuk-visually-hidden"> upload</span>
                </a>
            </dd>
        </div>
    }

    @if (!Model.HasPlanningPermission)
    {
        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Permission not required upload
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.PlanningPermissionFileName
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="exempt-upload">
                    Change<span class="govuk-visually-hidden"> upload</span>
                </a>
            </dd>
        </div>
    }
    </dl>

    <h2 class="govuk-heading-m">Production details</h2>

    <dl class="govuk-summary-list govuk-!-margin-bottom-9">
        <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
            Volume of biomethane
        </dt>
        <dd class="govuk-summary-list__value">
            @Model.MaxCapacity
        </dd>
        <dd class="govuk-summary-list__actions">
            <a class="govuk-link" href="@UrlKeys.ProductionDetailsMaximumInitialCapacity">
                Change<span class="govuk-visually-hidden"> production details</span>
            </a>
        </dd>
        </div>
        <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
            Expected start date
        </dt>
        <dd class="govuk-summary-list__value">
            @Model.InjectionStartDay @Model.InjectionStartMonth  @Model.InjectionStartYear
        </dd>
        <dd class="govuk-summary-list__actions">
            <a class="govuk-link" href="@UrlKeys.ProductionDetailsMaximumInitialCapacity">
                Change<span class="govuk-visually-hidden"> production details</span>
            </a>
        </dd>
        </div>
    </dl>


    <h2 class="govuk-heading-m">Now send your application</h2>

    <p class="govuk-body">
        By submitting this notification you are confirming that, to the best of your knowledge, the
        details you are providing are correct.
    </p>

    <p>
        <div class="govuk-button-group">
            @await Html.GovUkButton(new ButtonViewModel
       {
           Text = "Accept and submit"
       })
        </div>
    </p>

    </div>
    </div>
    </div>

</form>

ExternalPortal/Views/StageOne/Confirmation.cshtml
@model ExternalPortal.ViewModels.InstallationModel

@{
    ViewData["Title"] = "Stage One - Confirmation";
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        <div class="govuk-panel govuk-panel--confirmation">
            <h1 class="govuk-panel__title">Stage 1 complete</h1>
        </div>

        <p>
            We've received your application and sent you a confirmation email.
        </p>

        <h2 class="govuk-heading-m">What happens next</h2>

        <p>
            We'll contact you to confirm your registration, or to ask for more information.
        </p>

        @if (Model.BackLink != null)
        {
            await Html.RenderPartialAsync("Components/ReturnToYourApplication", Model.BackLink);
        }

    </div>
</div>

ExternalPortal/Views/StageOne/EquipmentDescription.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.PlantDetailsModel

@{
    ViewData["Title"] = "Stage One - Give a description of the equipment used to produce biomethane";

    await Html.RenderPartialAsync("Components/ViewBackLink");
}

<form action="@UrlKeys.EquipmentDescriptionLink" method="post">

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <div class="govuk-form-group">
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                        <label for="EquipmentDescription">
                            <h1 class="govuk-fieldset__heading">
                                Give a description of the equipment used to produce biomethane
                            </h1>
                        </label>
                    </legend>

                    <p class="govuk-body">
                        This description should include details of:
                        <ul class="govuk-list govuk-list--bullet">
                            <li>equipment required to convert raw biogas into biomethane suitable for injection</li>
                            <li>equipment to remove CO2 and other elements</li>
                            <li>pressurisation equipment</li>
                            <li>propanation equipment</li>
                            <li>odorant equipment</li>
                            <li>anaerobic digester(s)</li>
                            <li>any other equipment which is integral to the production of biomethane for injection</li>
                        </ul>
                    </p>

                    <div class="govuk-form-group">
                        @await Html.GovUkTextAreaFor(m => m.EquipmentDescription)
                    </div>
                </fieldset>
                <p>
                    <div class="govuk-button-group">
                        @await Html.GovUkButton(new ButtonViewModel
                   {
                       Text = "Save and continue"
                   })
                    </div>
                    @if (Model.BackLink != null)
                    {
                        await Html.RenderPartialAsync("Components/ReturnToYourApplication", Model.BackLink);
                    }
                </p>
            </div>
        </div>
    </div>
</form>

ExternalPortal/Views/StageOne/FeedstockSelfSupply.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents
@model StageOneModel
@{
    ViewData["Title"] = "Stage One - Self Supply";
}
<form action="self-supply" method="post" novalidate>
    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <div class="govuk-form-group">
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                        <h1 class="govuk-fieldset__heading">
                            Owner of the plant supplying feedstock
                        </h1>
                    </legend>
                    <div id="more-detail-hint" class="govuk-hint">
                        Tell us the name of the person who will do this.
                    </div>

                    <div class="govuk-form-group">
                        @await Html.GovUkTextInputFor(m => m.FeedstockSelfSupplyName,
                        classes: "govuk-input govuk-input--width-20")
                    </div>

                    <div id="start-hint" class="govuk-hint">
                        Ofgem will ask for evidence that feedstock can be supplied sustainably before you are registered on the
                        scheme.
                    </div>
                </fieldset>
                <p>
                    <div class="govuk-button-group">
                        @await Html.GovUkButton(new ButtonViewModel
                   {
                       Text = "Continue"
                   })
                    </div>
                </p>
            </div>
        </div>
    </div>
</form>

ExternalPortal/Views/StageOne/ProductionDetails.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents
@model StageOneModel
@{
    ViewData["Title"] = "Stage One - Production details";
}

@using (Html.BeginForm("ProductionDetails", "StageOne", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <div class="govuk-form-group">
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                        <h1 class="govuk-fieldset__heading">
                            Enter the maximum initial capacity of biomethane you plan to inject per year
                        </h1>
                    </legend>
                    <div id="more-detail-hint" class="govuk-hint">
                        Enter the volume in cubic metres over 12 months from the date you plan to begin injecting biomethane into the gas grid.
                    </div>

                    <div class="govuk-form-group">
                        @await Html.GovUkTextInputFor(m => m.MaxCapacity,
                            classes: "govuk-input govuk-input--width-20")
                    </div>

                </fieldset>
                <p>
                    <div class="govuk-button-group">
                        @await Html.GovUkButton(new ButtonViewModel
                   {
                       Text = "Save and continue"
                   })
                    </div>
                </p>
            </div>
        </div>
    </div>
}