ExternalPortal/ViewModels/CheckAnswersViewModel.cs
using ExternalPortal.Enums;
using System;
using System.Collections.Generic;

namespace ExternalPortal.ViewModels
{
    public class CheckAnswersViewModel
    {
        public Guid OrganisationId { get; set; }
        public TaskType TaskType { get; set; }
        public string BackAction { get; set; }
        public List<Answer> Answers { get; set; }

        public CheckAnswersViewModel(TaskType taskType)
        {
            this.TaskType = taskType;
            this.Answers = new List<Answer>();
        }
    }

    public struct Answer
    {
        public TaskPropertyName PropertyName { get; set; }
        public string PropertyValue { get; set; }
        public string ChangeLink { get; set; }
    }
}

ExternalPortal/ViewModels/Organisation/EnterOrgDetailsViewModel.cs
using GovUkDesignSystem.Attributes.ValidationAttributes;
using Ofgem.API.GGSS.Domain.Enums;

namespace ExternalPortal.ViewModels.Organisation
{
    public class EnterOrgDetailsViewModel
    {
        [GovUkValidateRequired(ErrorMessageIfMissing = "Enter organisation name")]
        public string Name { get; set; }
        [GovUkValidateRequired(ErrorMessageIfMissing = "Enter building and street")]
        public string LineOne { get; set; }
        public string LineTwo { get; set; }
        [GovUkValidateRequired(ErrorMessageIfMissing = "Enter town or city")]
        public string Town { get; set; }
        public string County { get; set; }
        [GovUkValidateRequired(ErrorMessageIfMissing = "Enter postcode")]
        public string Postcode { get; set; }
        public OrganisationType? Type { get; set; }
        public string ReturnUrl { get; set; }

    }
}

ExternalPortal/Controllers/OrganisationController.cs
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExternalPortal.Constants;
using ExternalPortal.Extensions;
using ExternalPortal.Helpers;
using ExternalPortal.Models;
using ExternalPortal.Services;
using ExternalPortal.ViewModels;
using ExternalPortal.ViewModels.Organisation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Ofgem.API.GGSS.Domain.Commands.Organisations;
using Ofgem.API.GGSS.Domain.Enums;
using Ofgem.API.GGSS.Domain.Models;
using Ofgem.API.GGSS.Domain.ModelValues;
using Ofgem.GovUK.Notify.Client;

namespace ExternalPortal.Controllers
{
    public class OrganisationController : BaseController
    {
        private readonly ILogger<OrganisationController> _logger;
        private readonly IGetCompaniesHouseService _getCompaniesHouseService;
        private readonly IDeleteDocumentService _deleteDocumentService;
        private readonly ISaveDocumentService _saveDocumentService;
        private readonly IOrganisationService _organisationService;
        private readonly ISendEmailService _sendEmailService;
        private readonly IGetUserByProviderIdService _getUserByProviderIdService;
        private readonly IOptions<SendEmailConfig> _sendEmailConfig;

        public OrganisationController(ILogger<OrganisationController> logger,
            IGetCompaniesHouseService getCompaniesHouseService,
            IRedisCacheService redisCache,
            IDeleteDocumentService deleteDocumentService,
            ISaveDocumentService saveDocumentService,
            IOrganisationService organisationService,
            ISendEmailService sendEmailService,
            IGetUserByProviderIdService getUserByProviderIdService,
            IOptions<SendEmailConfig> sendEmailConfig) : base(redisCache)
        {
            _logger = logger;
            _getCompaniesHouseService = getCompaniesHouseService;
            _deleteDocumentService = deleteDocumentService;
            _saveDocumentService = saveDocumentService;
            _organisationService = organisationService;
            _sendEmailService = sendEmailService;
            _getUserByProviderIdService = getUserByProviderIdService;
            _sendEmailConfig = sendEmailConfig;
        }

        [Route(UrlKeys.RegisterAnOrganisation)]
        public IActionResult Index()
        {
            _logger.LogDebug("Index action on Organisation controller called");

            return View("Index");
        }

        [AllowAnonymous]
        [Route(UrlKeys.RegisterBeforeYouApply)]
        public IActionResult BeforeYouApply()
        {
            _logger.LogDebug("BeforeYouApply action on Organisation controller called");

            return View();
        }

        #region Organisation Type

        [HttpGet]
        public async Task<IActionResult> ChooseType(CancellationToken token)
        {
            var cacheModel = await RedisCache.GetOrgRegistrationAsync(UserId, token);
            cacheModel.ReturnUrl = HttpContext.Request.Query["change"];
            return View(nameof(ChooseType), cacheModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChooseType(PortalViewModel<OrganisationModel> viewModel, CancellationToken token)
        {
            if (viewModel.Model.Value.Type == null)
            {
                return RedirectToAction(nameof(Start), viewModel);
            }

            _ = await RedisCache.SaveOrgRegistrationAsync(UserId, "Model.Value.Type", (OrganisationType)viewModel.Model.Value.Type, token);

            return viewModel.Model.Value.Type == OrganisationType.Private ?
                 RedirectToAction(nameof(Start), new PortalViewModel<OrganisationModel>{ReturnUrl = viewModel.ReturnUrl}) :
                 RedirectToAction("EnterOrgDetails", new PortalViewModel<OrganisationModel>{ReturnUrl = viewModel.ReturnUrl});
        }

        #endregion Organisation Type

        #region Companies House Lookup

        [HttpGet]
        public async Task<IActionResult> Start(PortalViewModel<OrganisationModel> viewModel)
        {
            var model = await RedisCache.GetOrgRegistrationAsync(UserId, CancellationToken.None);

            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }

            model.ReturnUrl = string.IsNullOrEmpty(viewModel.ReturnUrl) ? HttpContext.Request.Query["returnUrl"].ToString() : viewModel.ReturnUrl;

            return View("Start", model);
        }

        [HttpPost]
        public async Task<IActionResult> Start(PortalViewModel<OrganisationModel> viewModel, CancellationToken token)
        {
            var registrationNumber = viewModel?.Model?.Value?.RegistrationNumber;

            if (string.IsNullOrWhiteSpace(registrationNumber))
            {
                if (viewModel == null)
                {
                    viewModel = new PortalViewModel<OrganisationModel>();
                }

                viewModel.AddError("Enter your company registration number");

                return View("Start", viewModel);
            }

            var response = await _getCompaniesHouseService.GetCompanyDetailsAsync(registrationNumber);

            if (response.Errors.Any())
            {
                viewModel.AddError(response.Errors.First());

                return View("Start", viewModel);
            }

            var organisationModel = await RedisCache.GetOrgRegistrationAsync(UserId, token);

            organisationModel.Model.Value.RegistrationNumber = response.Model.Value.RegistrationNumber;
            organisationModel.Model.Value.Name = response.Model.Value.Name;
            organisationModel.Model.Value.RegisteredOfficeAddress = response.Model.Value.RegisteredOfficeAddress;

            _ = await RedisCache.SaveOrgRegistrationAsync(UserId, "Model", organisationModel.Model, token);

            return RedirectToAction(nameof(Confirm), new PortalViewModel<OrganisationModel>{ReturnUrl = viewModel.ReturnUrl});
        }
        
        [HttpGet]
        public async Task<IActionResult> Confirm(PortalViewModel<OrganisationModel> viewModel = null)
        {
            var model = await RedisCache.GetOrgRegistrationAsync(UserId, CancellationToken.None);

            model.ReturnUrl = viewModel.ReturnUrl;

            return View("Confirm", model);
        }

        [HttpPost]
        public async Task<IActionResult> Confirm(PortalViewModel<OrganisationModel> viewModel, string submit, CancellationToken token)
        {
            if (submit == null)
            {
                viewModel.AddError("Select an option");

                var organisationModel = await RedisCache.GetOrgRegistrationAsync(UserId, token);

                viewModel.Model = organisationModel.Model;

                return View(nameof(Confirm), viewModel);
            }

            if (submit == "cancel")
            {
                return RedirectToAction(nameof(Start), viewModel);
            }

            if (!string.IsNullOrEmpty(viewModel.ReturnUrl))
            {
                return RedirectToAction(nameof(CheckAnswers));
            }
            
            return RedirectToAction("Index", "ResponsiblePerson");
        }
        
        #endregion Companies House Lookup

        #region Organisation details

        [HttpGet]
        public async Task<IActionResult> EnterOrgDetails(CancellationToken token, PortalViewModel<OrganisationModel> viewModel = null)
        {
            var vm = await RedisCache.GetOrgRegistrationAsync(UserId, token);
            string queryString = string.IsNullOrEmpty(viewModel.ReturnUrl) ? HttpContext.Request.Query["returnUrl"].ToString() : viewModel.ReturnUrl;

            return View(nameof(EnterOrgDetails), new EnterOrgDetailsViewModel
            {
                Name = vm.Model.Value.Name,
                LineOne = vm.Model.Value.RegisteredOfficeAddress.LineOne,
                LineTwo = vm.Model.Value.RegisteredOfficeAddress.LineTwo,
                Town = vm.Model.Value.RegisteredOfficeAddress.Town,
                County = vm.Model.Value.RegisteredOfficeAddress.County,
                Postcode = vm.Model.Value.RegisteredOfficeAddress.Postcode,
                Type = vm.Model.Value.Type,
                ReturnUrl = queryString
            });
        }

        [HttpPost]
        public async Task<IActionResult> EnterOrgDetails(EnterOrgDetailsViewModel viewModel, CancellationToken token)
        {
            if (ModelState.IsValid)
            {
                return await SaveOrganisationAsync(viewModel, token);
            }
                
            return View(nameof(EnterOrgDetails), viewModel);
        }

        #endregion Organisation details

        [HttpGet]
        [Route(UrlKeys.LetterOfAuthorisation)]
        public async Task<IActionResult> LetterOfAuthorityUpload(CancellationToken token, PortalViewModel<OrganisationModel> viewModel = null)
        {
            var model = await RedisCache.GetOrgRegistrationAsync(UserId, token);

            string queryString = string.IsNullOrEmpty(viewModel.ReturnUrl) ? HttpContext.Request.Query["returnUrl"].ToString() : viewModel.ReturnUrl;
            
            if (model == null)
            {
                return View(nameof(Start));
            }

            model.ReturnUrl = queryString;

            return View(nameof(LetterOfAuthorityUpload), model);
        }

        [HttpPost]
        [Route(UrlKeys.LetterOfAuthorisation)]
        public async Task<IActionResult> LetterOfAuthorityUpload(IFormFile letterOfAuthorisation, CancellationToken token, [FromForm] PortalViewModel<OrganisationModel> viewModel = null)
        {
            var model = await RedisCache.GetOrgRegistrationAsync(UserId, token);
            
            var response = await _saveDocumentService.Save(letterOfAuthorisation, token);

            if (response.HasErrors)

ExternalPortal/Views/Organisation/CheckAnswers.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model PortalViewModel<Ofgem.API.GGSS.Domain.Models.OrganisationModel>

@{
    ViewData["Title"] = "Register an organisation - Check Answers";

    <p><a href="javascript:history.go(-1)" class="govuk-back-link">Back</a></p>
}
@using (Html.BeginForm("CheckAnswers", "Organisation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-l">Check your answers</h1>

            <h2 class="govuk-heading-m">Organisation details</h2>
            <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">Type</dt>
                <dd class="govuk-summary-list__value">@Model.Model.Value.Type.GetDisplayName()</dd>
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/choose-type?returnUrl=check-answers&change=type">
                        Change<span class="govuk-visually-hidden"> organisation type</span>
                    </a>
                </dd>
        </div>

        @if (Model.Model.Value.Type == OrganisationType.Private)
        {
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Companies House registration number (if a limited company)
                </dt>
                <dd class="govuk-summary-list__value">
                    @Model.Model.Value.RegistrationNumber
                </dd>
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/start?returnUrl=check-answers">
                        Change<span class="govuk-visually-hidden"> registration number</span>
                    </a>
                </dd>
            </div>
        }

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Name
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.Model.Value.Name
            </dd>

            @if (Model.Model.Value.Type == OrganisationType.Private)
            {
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/start?returnUrl=check-answers">
                        Change<span class="govuk-visually-hidden"> organisation name</span>
                    </a>
                </dd>
            }
            else
            {
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/enter-org-details?returnUrl=check-answers">
                        Change<span class="govuk-visually-hidden"> organisation name</span>
                    </a>
                </dd>
            }

        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Address
            </dt>
            <dd class="govuk-summary-list__value">
                <p class="govuk-body">@Model.Model.Value.RegisteredOfficeAddress.LineOne</p>
                <p class="govuk-body">@Model.Model.Value.RegisteredOfficeAddress.LineTwo</p>
                <p class="govuk-body">@Model.Model.Value.RegisteredOfficeAddress.Town</p>
                <p class="govuk-body">@Model.Model.Value.RegisteredOfficeAddress.County</p>
                <p class="govuk-body">@Model.Model.Value.RegisteredOfficeAddress.Postcode</p>
            </dd>
            @if (Model.Model.Value.Type == OrganisationType.Private)
            {
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/start?returnUrl=check-answers">
                        Change<span class="govuk-visually-hidden"> organisation address</span>
                    </a>
                </dd>
            }
            else
            {
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/enter-org-details?returnUrl=check-answers">
                        Change<span class="govuk-visually-hidden">organisation address</span>
                    </a>
                </dd>
            }
        </div>

        @if (Model.Model.Value.Type == OrganisationType.Other)
        {
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Legal document
                </dt>
                <dd class="govuk-summary-list__value">
                    @Model.Model.Value.LegalDocument.FileName
                </dd>
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="/organisation/legal-doc-upload?returnUrl=check-answers">
                        Change<span class="govuk-visually-hidden"> legal document</span>
                    </a>
                </dd>
            </div>
        }

        </dl>
    </div>
    </div>

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h2 class="govuk-heading-m">Authorised signatory details</h2>
            <dl class="govuk-summary-list govuk-!-margin-bottom-9">

                <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Name
                </dt>
                <dd class="govuk-summary-list__value">
                    @Model.Model.ResponsiblePeople.FirstOrDefault().User?.Value.GetFullName()
                </dd>
                <dd class="govuk-summary-list__actions">
                </dd>
        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Phone number
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.Model.ResponsiblePeople.FirstOrDefault().Value.TelephoneNumber
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="/responsible-person/phone-number?returnUrl=check-answers">
                    Change<span class="govuk-visually-hidden"> phone number</span>
                </a>
            </dd>
        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Email address
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.Model.ResponsiblePeople.First().User?.Value.EmailAddress
            </dd>
            <dd class="govuk-summary-list__actions">
            </dd>
        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Date of birth
            </dt>
            <dd class="govuk-summary-list__value">
                @Convert.ToDateTime(Model.Model.ResponsiblePeople.FirstOrDefault().Value.DateOfBirth).ToString("dd MM yyyy")
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="/responsible-person/date-of-birth?returnUrl=check-answers">
                    Change<span class="govuk-visually-hidden"> date of birth</span>
                </a>
            </dd>
        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Letter of authorisation
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.Model.Value.LetterOfAuthorisation.FileName
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="@UrlKeys.LetterOfAuthorisation?returnUrl=check-answers">
                    Change<span class="govuk-visually-hidden"> letter of authorisation</span>
                </a>
            </dd>
        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Photo ID
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.Model.Value.PhotoId.FileName
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="/organisation/photo-id-upload?returnUrl=check-answers">
                    Change<span class="govuk-visually-hidden"> photo id</span>
                </a>
            </dd>
        </div>

        <div class="govuk-summary-list__row">
            <dt class="govuk-summary-list__key">
                Evidence of home address
            </dt>
            <dd class="govuk-summary-list__value">
                @Model.Model.Value.ProofOfAddress.FileName
            </dd>
            <dd class="govuk-summary-list__actions">
                <a class="govuk-link" href="/organisation/proof-of-address-upload">
                    Change<span class="govuk-visually-hidden"> proof of address</span>
                </a>
            </dd>
        </div>
        </dl>

        <p>
            <div class="govuk-button-group">
                @await Html.GovUkButton(new ButtonViewModel { Text = "Submit" })
            </div>
        </p>

    </div>
    </div>

}

ExternalPortal/Views/Organisation/ChooseType.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents
@using Ofgem.API.GGSS.Domain.Enums

@model PortalViewModel<Ofgem.API.GGSS.Domain.Models.OrganisationModel>


@{
    ViewData["Title"] = "Choose an organisation type";

    await Html.RenderPartialAsync("Components/ViewBackLink");
}

@using (Html.BeginForm("ChooseType", "Organisation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <div>
                <div class="govuk-form-group">
                    @await Html.GovUkRadiosFor(m => m.Model.Value.Type,
                    new FieldsetViewModel
                    {
                        Legend = new LegendViewModel
                        {
                            Text = "Choose an organisation type",
                            Classes = "govuk-fieldset__legend govuk-fieldset__legend--l"
                            ,IsPageHeading = true
                        }
                    },
                    radioHints: new Dictionary<OrganisationType, HintViewModel>
                    {
                        { OrganisationType.Private, new HintViewModel { Text="This is a company which is registered at Companies House." } },
                        { OrganisationType.Other, new HintViewModel { Text="This is a private individual or organisation which is not registered at Companies House." } }
                    }
                    )
                </div>
            </div>

            <div class="govuk-button-group">
                @await Html.GovUkButton(new ButtonViewModel { Text = "Continue" })
            </div>
        </div>
    </div>
    @Html.HiddenFor(m => m.ReturnUrl)
}

ExternalPortal/Views/Organisation/EnterOrgDetails.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Organisation.EnterOrgDetailsViewModel

@{
    var error = !ViewData.ModelState.IsValid ? "Error:" : "";

    ViewData["Title"] = $"{@error} Enter Organisation Details";

    await Html.RenderPartialAsync("Components/ViewBackLink");
}

@await Html.GovUkErrorSummary(ViewData.ModelState)

@using (Html.BeginForm("EnterOrgDetails", "Organisation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <div>
                <div class="govuk-form-group">
                    <fieldset class="govuk-fieldset">
                        <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                            <h1 class="govuk-fieldset__heading">Tell us the organisation's name and address</h1>
                        </legend>

                        <div class="govuk-form-group">
                            @await Html.GovUkTextInputFor(m => m.Name,
                            classes: "govuk-input",
                            labelOptions: new LabelViewModel { Text = "Organisation name" })
                        </div>

                        <div class="govuk-form-group">
                            @await Html.GovUkTextInputFor(m => m.LineOne,
                            classes: "govuk-input",
                            labelOptions: new LabelViewModel { Text = "Building and street" })
                            <span class="govuk-visually-hidden">line 1 of 2</span>
                        </div>

                        <div class="govuk-form-group">
                            @await Html.GovUkTextInputFor(m => m.LineTwo,
                            classes: "govuk-input",
                            labelOptions: new LabelViewModel { Text = "" })
                            <span class="govuk-visually-hidden">Building and street line 2 of 2</span>
                        </div>

                        <div class="govuk-form-group">
                            @await Html.GovUkTextInputFor(m => m.Town,
                            classes: "govuk-input govuk-!-width-two-thirds",
                            labelOptions: new LabelViewModel { Text = "Town or city" })
                        </div>

                        <div class="govuk-form-group">
                            @await Html.GovUkTextInputFor(m => m.County,
                            classes: "govuk-input govuk-!-width-two-thirds",
                            labelOptions: new LabelViewModel { Text = "County" })
                        </div>

                        <div class="govuk-form-group">
                            @await Html.GovUkTextInputFor(m => m.Postcode,
                            classes: "govuk-input govuk-input--width-10",
                            labelOptions: new LabelViewModel { Text = "Postcode" })
                        </div>
                        @Html.HiddenFor(m => m.Type)
                        @Html.HiddenFor(m => m.ReturnUrl)
                    </fieldset>
                </div>
            </div>

            <div class="govuk-button-group">
                @await Html.GovUkButton(new ButtonViewModel { Text = "Continue" })
            </div>
        </div>
    </div>
}

ExternalPortal/Views/Organisation/LetterOfAuthorityUpload.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model PortalViewModel<Ofgem.API.GGSS.Domain.Models.OrganisationModel>

@{
    ViewData["Title"] = "Letter of authorisation";

    if (Model.HasErrors) 
    {
        Model.InPageLink = "#letterOfAuthorisation";
        await Html.RenderPartialAsync("_ErrorPartial", Model);
    } 

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var formError = String.IsNullOrEmpty(Model.Model.Value.Error) ? "" : "govuk-form-group--error";
}

@using (Html.BeginForm("LetterOfAuthorityUpload", "Organisation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <fieldset class="govuk-fieldset">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                    <h1 class="govuk-fieldset__heading">
                        Give us a letter of authorisation
                    </h1>
                </legend>

                <details class="govuk-details" data-module="govuk-details">
                    <summary class="govuk-details__summary">
                        <span class="govuk-details__summary-text">
                            Help with letter of authorisation
                        </span>
                    </summary>
                    <div class="govuk-details__text">
                        <p>A letter of authorisation (LOA) is a document where an organisation confirms who the authorised signatory is and that they have the authority to act on behalf of the organisation.</p>

                        <p>It must be uploaded when you register your organisation with Ofgem, before starting your application for GGSS.</p>

                        <p>The details of the authorised signatory given on the LOA will be cross-checked against the personal details the authorised signatory has provided.</p>

                        <p>We've <a href="https://www.ofgem.gov.uk/publications/green-gas-support-scheme-letter-authorisation">more details on the LOA and a template for you to use (opens in a new tab)</a>.</p>
                    </div>
                </details>

                <div class="govuk-form-group @formError">
                    @{
                        if (!String.IsNullOrEmpty(Model.Model.Value.Error))
                        {
                            <span id="letter-of-authorisation-upload-error" class="govuk-error-message">
                                @Model.Model.Value.Error
                            </span>
                        }
                    }
                    <label class="govuk-label" for="letterOfAuthorisation">
                        Upload a file
                    </label>
                    <input class="govuk-file-upload" id="letterOfAuthorisation" name="letterOfAuthorisation" type="file" aria-describedby="letter-of-authorisation">
                </div>

                <p class="govuk-body">
                    You can only upload PDF, JPG, PNG, BMP, TIF, XLS or XLSX files. No file can be larger than 5MB.
                </p>

                @Html.HiddenFor(m => m.ReturnUrl)
            </fieldset>

            <div class="govuk-button-group">
                @await Html.GovUkButton(new ButtonViewModel { Text = "Continue" })
            </div>

        </div>
    </div>
}

ExternalPortal/Views/Organisation/Start.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model PortalViewModel<Ofgem.API.GGSS.Domain.Models.OrganisationModel>

@{
    ViewData["Title"] = Model.HasErrors ? "Error: Register organisation" : "Register organisation";
    var formCss = Model.HasErrors ? "govuk-form-group govuk-form-group--error" : "govuk-form-group";
    var inputCss = Model.HasErrors ? "govuk-input govuk-input--width-10 govuk-input--error" : "govuk-input govuk-input--width-10";
}

<a href="javascript:history.go(-1)" class="govuk-back-link">Back</a>

@using (Html.BeginForm("Start", "Organisation", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading-l">Your company's registration number</h1>

            <p class="govuk-body">
                You can search <a href="https://find-and-update.company-information.service.gov.uk/"
                                  target="_blank">Companies House (opens in a new tab)</a> for your Company Registration Number (CRN).
            </p>

            <div class="govuk-form-group">
                <div id="companies-house-hint" class="govuk-hint">
                    Your Company Registration Number (CRN) is 8 characters long.
                </div>

                <div class="@formCss">
                    @{
                        if (Model.HasErrors)
                        {
                            <span id="companies-house-error" class="govuk-error-message">
                                Not Found
                            </span>
                        }
                    }

                    @await Html.GovUkTextInputFor(m => m.Model.Value.RegistrationNumber, classes: @inputCss)
                </div>

            </div>

            <div class="govuk-button-group">
                @await Html.GovUkButton(new ButtonViewModel { Text = "Continue" })
            </div>

        </div>
    </div>
    @Html.HiddenFor(m => m.ReturnUrl)
}