ExternalPortal/ViewModels/CheckAnswersViewModel.cs
using ExternalPortal.Enums;
using System;
using System.Collections.Generic;

namespace ExternalPortal.ViewModels
{
    public class CheckAnswersViewModel
    {
        public Guid OrganisationId { get; set; }
        public TaskType TaskType { get; set; }
        public string BackAction { get; set; }
        public List<Answer> Answers { get; set; }

        public CheckAnswersViewModel(TaskType taskType)
        {
            this.TaskType = taskType;
            this.Answers = new List<Answer>();
        }
    }

    public struct Answer
    {
        public TaskPropertyName PropertyName { get; set; }
        public string PropertyValue { get; set; }
        public string ChangeLink { get; set; }
    }
}

ExternalPortal/Controllers/SupportingEvidenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ExternalPortal.Constants;
using ExternalPortal.Helpers;
using ExternalPortal.Services;
using ExternalPortal.ViewModels.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ofgem.API.GGSS.Domain.ModelValues;
using TaskStatus = ExternalPortal.Enums.TaskStatus;

namespace ExternalPortal.Controllers
{
    public class SupportingEvidenceController : ApplicationController
    {
        private readonly ILogger<SupportingEvidenceController> _logger;
        private readonly ISaveDocumentService _saveDocumentService;
        private readonly IDeleteDocumentService _deleteDocumentService;

        public SupportingEvidenceController(
            ILogger<SupportingEvidenceController> logger,
            ISaveDocumentService saveDocumentService,
            IDeleteDocumentService deleteDocumentService,
            IGetApplicationService getApplicationService,
            IUpdateApplicationService updateApplicationService) : base(getApplicationService, updateApplicationService)
        {
            _logger = logger;
            _saveDocumentService = saveDocumentService;
            _deleteDocumentService = deleteDocumentService;
        }

        [HttpGet]
        [Route(UrlKeys.SupportingEvidenceWhatYouWillNeed)]
        public IActionResult WhatYouWillNeed()
        {
            _logger.LogInformation("WhatYouWillNeed action called on SupportingEvidence controller");

            return View(nameof(WhatYouWillNeed));
        }

        [HttpGet]
        [Route(UrlKeys.SupportingEvidenceAdd)]
        public async Task<IActionResult> AddSupportingEvidence()
        {
            _logger.LogInformation("AddSupportingEvidence action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            if (application.StageTwo.AdditionalSupportingEvidence.Status == TaskStatus.NotStarted.ToString())
            {
                application.StageTwo.AdditionalSupportingEvidence.Status = TaskStatus.InProgress.ToString();
            }

            await PersistApplicationToApi(application);

            var model = new AdditionalFinancialEvidenceModel()
            {
                AddEvidence = application.StageTwo.AdditionalSupportingEvidence.AddEvidence
            };

            return View(nameof(AddSupportingEvidence), model);
        }

        [HttpPost]
        [Route(UrlKeys.SupportingEvidenceAdd)]
        public async Task<IActionResult> AddSupportingEvidence(string supportingEvidence, CancellationToken token)
        {
            _logger.LogInformation("AddSupportingEvidence action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            if (string.IsNullOrWhiteSpace(supportingEvidence))
            {
                var model = new AdditionalFinancialEvidenceModel
                {
                    Error = "Select an option"
                };

                return View(nameof(AddSupportingEvidence), model);
            }

            application.StageTwo.AdditionalSupportingEvidence.AddEvidence = supportingEvidence;

            await PersistApplicationToApi(application);

            if (IsOptionNo(supportingEvidence))
            {
                var documents = application.StageTwo.AdditionalSupportingEvidence.AdditionalSupportingEvidenceDocuments;

                documents?.ForEach(async document => _ = await _deleteDocumentService.Delete(document.FileId, token));

                application.StageTwo.AdditionalSupportingEvidence.AdditionalSupportingEvidenceDocuments = new List<DocumentValue>();

                await PersistApplicationToApi(application);
                
                return RedirectToAction(nameof(CheckAnswers));
            }

            return RedirectToAction(nameof(Upload));
        }

        [HttpGet]
        [Route(UrlKeys.SupportingEvidenceUpload)]
        public async Task<IActionResult> Upload()
        {
            _logger.LogInformation("Upload action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            if (application.StageTwo.AdditionalSupportingEvidence.Status == TaskStatus.NotStarted.ToString())
            {
                application.StageTwo.AdditionalSupportingEvidence.Status = TaskStatus.InProgress.ToString();

                await PersistApplicationToApi(application);
            }

            return View(nameof(Upload), new AdditionalFinancialEvidenceModel());
        }

        [HttpPost]
        [Route(UrlKeys.SupportingEvidenceUpload)]
        public async Task<IActionResult> Upload(IFormFile supportingEvidenceFile, CancellationToken token)
        {
            _logger.LogInformation("Upload action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            var response = await _saveDocumentService.Save(supportingEvidenceFile, token);

            if (response.HasErrors)
            {
                var model = new AdditionalFinancialEvidenceModel()
                {
                    Error = response.Errors.Select(e => e.Message).First()
                };

                return View(nameof(Upload), model);
            }

            application.StageTwo.AdditionalSupportingEvidence.AdditionalSupportingEvidenceDocuments.Add(new Ofgem.API.GGSS.Domain.ModelValues.DocumentValue()
            {
                FileId = response.DocumentId,
                FileName = supportingEvidenceFile.FileName,
                FileSizeAsString =  FileSizeHelper.GetFileSizeAsString(supportingEvidenceFile.Length),
                Tags = DocumentTags.SupportingEvidence
            });

            await PersistApplicationToApi(application);

            return RedirectToAction(nameof(UploadConfirm));
        }

        [HttpGet]
        [Route(UrlKeys.SupportingEvidenceUploadConfirm)]
        public async Task<IActionResult> UploadConfirm()
        {
            _logger.LogInformation("Upload action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            var model = GetAdditionalFinancialEvidenceModel(application);

            return View(nameof(UploadConfirm), model);
        }

        [HttpPost]
        [Route(UrlKeys.SupportingEvidenceUploadConfirm)]
        public async Task<IActionResult> UploadConfirm(string option, string documentId, CancellationToken token)
        {
            _logger.LogInformation("UploadConfirm action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            if (string.IsNullOrWhiteSpace(option))
            {
                var model = GetAdditionalFinancialEvidenceModel(application);

                model.Error = "Select an option";

                return View(nameof(UploadConfirm), model);
            }

            if (IsOptionNo(option))
            {
                await _deleteDocumentService.Delete(documentId, token);

                application.StageTwo.AdditionalSupportingEvidence.AdditionalSupportingEvidenceDocuments
                    .RemoveAll(d => d.FileId == documentId);

                await PersistApplicationToApi(application);

                return RedirectToAction(nameof(Upload));
            }

            return RedirectToAction(nameof(AddReference));
        }

        [HttpGet]
        [Route(UrlKeys.SupportingEvidenceAddReference)]
        public async Task<IActionResult> AddReference()
        {
            _logger.LogInformation("AddReference action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            var model = GetAdditionalFinancialEvidenceModel(application);

            return View(nameof(AddReference), model);
        }

        [HttpPost]
        [Route(UrlKeys.SupportingEvidenceAddReference)]
        public async Task<IActionResult> AddReference(string reference, string documentId, CancellationToken token)
        {
            _logger.LogInformation("UploadConfirm action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            if (string.IsNullOrWhiteSpace(reference))
            {
                var model = GetAdditionalFinancialEvidenceModel(application);

                model.Error = "Enter a reference";

                return View(nameof(AddReference), model);
            }

            application.StageTwo.AdditionalSupportingEvidence.AdditionalSupportingEvidenceDocuments
                .First(d => d.FileId == documentId).Reference = reference;

            await PersistApplicationToApi(application);

            return RedirectToAction(nameof(UploadMore));
        }

        [HttpGet]
        [Route(UrlKeys.SupportingEvidenceAddMore)]
        public async Task<IActionResult> UploadMore()
        {
            _logger.LogInformation("UploadMore action called on SupportingEvidence controller");

            var application = await RetrieveCurrentApplicationFromApi();

            var model = GetAdditionalFinancialEvidenceModel(application);

            return View(nameof(UploadMore), model);
        }

        [HttpPost]
        [Route(UrlKeys.SupportingEvidenceAddMore)]
        public async Task<IActionResult> UploadMore(string option, CancellationToken token)
        {
            _logger.LogInformation("UploadMore action called on SupportingEvidence controller");

            if (string.IsNullOrWhiteSpace(option))
            {
                var application = await RetrieveCurrentApplicationFromApi();

                var model = GetAdditionalFinancialEvidenceModel(application);

ExternalPortal/Views/SupportingEvidence/AddReference.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel
@{
    ViewData["Title"] = "Add reference";

    var formError = Model.HasError() ? "govuk-form-group--error" : "";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];

    var uploadedDocument = Model.Documents.Last();
}

@using (Html.BeginForm("AddReference", "SupportingEvidence", new { ApplicationId = @applicationId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <label class="govuk-label" for="Reference">
                <h1 class="govuk-fieldset__heading">
                    Add a reference for this file @uploadedDocument.Filename
                </h1>
            </label>
            <div id="more-detail-hint" class="govuk-hint">
                This will help us better identify documents if we need any more evidence.
            </div>

            <div class="govuk-form-group @formError">
                <fieldset class="govuk-fieldset">
                    @{
                        if (Model.HasError())
                        {
                            <span id="transport-upload-error" class="govuk-error-message">
                                @Model.Error
                            </span>
                        }
                    }

                    <input class="govuk-input" id="Reference" name="Reference" type="text" value="@uploadedDocument.Reference">
                </fieldset>
            </div>
        </div>
    </div>

    <div class="govuk-button-group">
        @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
    </div>

    @Html.Hidden("DocumentId", uploadedDocument.DocumentId, new { @id = "DocumentId" })
}

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/AddSupportingEvidence.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel

@{
    ViewData["Title"] = "Add supporting evidence Person";

    var formError = Model.HasError() ? "govuk-form-group--error" : "";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];
}

@using (Html.BeginForm("AddSupportingEvidence", "SupportingEvidence", new { ApplicationId = applicationId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <div class="govuk-form-group @formError">
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                        <h1 class="govuk-fieldset__heading">
                            Do you have any additional supporting evidence?
                        </h1>
                    </legend>

                    @{
                        if (Model.HasError())
                        {
                            <span id="transport-upload-error" class="govuk-error-message">
                                @Model.Error
                            </span>
                        }
                    }

                    <div class="govuk-radios">
                        <div class="govuk-radios__item">
                            <input class="govuk-radios__input" id="supportingEvidence-yes" name="supportingEvidence" type="radio" value="Yes">
                            <label class="govuk-label govuk-radios__label" for="supportingEvidence-yes">
                                Yes
                            </label>
                        </div>
                        <div class="govuk-radios__item">
                            <input class="govuk-radios__input" id="supportingEvidence-no" name="supportingEvidence" type="radio" value="No">
                            <label class="govuk-label govuk-radios__label" for="supportingEvidence-no">
                                No
                            </label>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>

    <div class="govuk-button-group">
        @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
    </div>

}

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/CheckAnswers.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel
@{
    ViewData["Title"] = "Check your answers";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];
}

@using (Html.BeginForm("SubmitYourAnswers", "SupportingEvidence", new { ApplicationId = applicationId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <h1 class="govuk-heading-l">Check your answers</h1>

            <h2 class="govuk-heading-m">Add additional evidence</h2>

            <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Add additional evidence
                </dt>
                <dd class="govuk-summary-list__value">
                    @Model.AddEvidence
                </dd>
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="@UrlKeys.SupportingEvidenceAdd?ApplicationId=@applicationId">
                        Change<span class="govuk-visually-hidden"> add additional evidence</span>
                    </a>
                </dd>
        </div>
        </dl>

        @{ if (Model.HasDocuments)
            {
                <h2 class="govuk-heading-m">Additional evidence documents</h2>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">

                    @foreach (var doc in Model.Documents)
                    {
                        <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            @doc.Reference
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <a href="@UrlKeys.DocumentDownload/@doc.DocumentId?ApplicationId=@applicationId">
                                @doc.Filename
                            </a>, (@doc.FileSizeAsString)
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <a class="govuk-link" href="@UrlKeys.SupportingEvidenceAddMore?ApplicationId=@applicationId">
                                Change<span class="govuk-visually-hidden"> @doc.Reference document</span>
                            </a>
                        </dd>
                        </div>
                    }
                </dl>
            }
        }

        </div>
        </div>

        <div class="govuk-button-group">
            @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
        </div>
    }

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/CheckYourAnswers.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel
@{
    ViewData["Title"] = "Check your answers";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];
}

@using (Html.BeginForm("SubmitYourAnswers", "SupportingEvidence", new { ApplicationId = applicationId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <h1 class="govuk-heading-l">Check your answers</h1>

            <h2 class="govuk-heading-m">Add additional evidence</h2>

            <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key">
                    Add additional evidence
                </dt>
                <dd class="govuk-summary-list__value">
                    @Model.AddEvidence
                </dd>
                <dd class="govuk-summary-list__actions">
                    <a class="govuk-link" href="@UrlKeys.SupportingEvidenceAdd?ApplicationId=@applicationId">
                        Change<span class="govuk-visually-hidden"> add additional evidence</span>
                    </a>
                </dd>
        </div>
        </dl>

        @{ if (Model.HasDocuments)
            {
                <h2 class="govuk-heading-m">Additional evidence documents</h2>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">

                    @foreach (var doc in Model.Documents)
                    {
                        <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key">
                            @doc.Reference
                        </dt>
                        <dd class="govuk-summary-list__value">
                            <a href="@UrlKeys.DocumentDownload/@doc.DocumentId?ApplicationId=@applicationId">
                                @doc.Filename
                            </a>, (@doc.FileSizeAsString)
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <a class="govuk-link" href="@UrlKeys.SupportingEvidenceAddMore?ApplicationId=@applicationId">
                                Change<span class="govuk-visually-hidden"> @doc.Reference document</span>
                            </a>
                        </dd>
                        </div>
                    }
                </dl>
            }
        }

        </div>
        </div>

        <div class="govuk-button-group">
            @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
        </div>
    }

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/DeleteDocument.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel
@{
    ViewData["Title"] = "Delete additional supporting evidence";

    var formError = Model.HasError() ? "govuk-form-group--error" : "";

    var fileName = (string)TempData["FileName"];
    var documentId = (string)TempData["DocumentId"];

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];
}

@using (Html.BeginForm("DeleteConfirm", "SupportingEvidence", new { ApplicationId = @applicationId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">

            <div class="govuk-form-group @formError">
                <fieldset class="govuk-fieldset">
                    <h1 class="govuk-heading">
                        Are you sure you want to remove @fileName?
                    </h1>

                    @{
                        if (Model.HasError())
                        {
                            <span id="transport-upload-error" class="govuk-error-message">
                                @Model.Error
                            </span>
                        }
                    }

                    <div class="govuk-radios">
                        @{
                            foreach (var option in Model.MoreOptions)
                            {
                                <div class="govuk-radios__item">
                                    <input class="govuk-radios__input" id="@option.Id"
                                           name="option" type="radio" value="@option.Value">
                                    <label class="govuk-label govuk-radios__label" for="@option.Id">
                                        @option.Text
                                    </label>
                                </div>
                            }
                        }
                    </div>

                </fieldset>
            </div>

        </div>
    </div>

    <div class="govuk-button-group">
        @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
    </div>

    @Html.Hidden("DocumentId", documentId, new { @id = "DocumentId" })
}

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/Upload.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel
@{
    ViewData["Title"] = "Upload supporting evidence";

    var formError = Model.HasError() ? "govuk-form-group--error" : "";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];
}

@using (Html.BeginForm("Upload", "SupportingEvidence", new { ApplicationId = @applicationId }, FormMethod.Post, true, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading">
                Upload your additional supporting evidence document
            </h1>

            <div id="more-detail-hint" class="govuk-hint">
                <p class="govuk-body">You can upload your documents as scanned copies or photos of the originals.</p>
                <p class="govuk-body">You can only upload PDF, JPG, PNG, BMP, TIF, XLS or XLSX files. No file can be larger than 5MB.</p>
            </div>
            <div class="govuk-form-group @formError">
                @{
                    if (Model.HasError())
                    {
                        <span id="transport-upload-error" class="govuk-error-message">
                            @Model.Error
                        </span>
                    }
                }
                <label class="govuk-label" for="supportingEvidenceFile">
                    Upload a file
                </label>
                <input type="file" class="govuk-file-upload" id="supportingEvidenceFile" name="supportingEvidenceFile" aria-describedby="file-upload-hint">
            </div>
        </div>
    </div>

    <div class="govuk-button-group">
        @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
    </div>
}

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/UploadConfirm.cshtml
@using GovUkDesignSystem
@using GovUkDesignSystem.GovUkDesignSystemComponents

@model ExternalPortal.ViewModels.Tasks.AdditionalFinancialEvidenceModel
@{
    ViewData["Title"] = "Confirm supporting evidence";

    var formError = Model.HasError() ? "govuk-form-group--error" : "";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];

    var uploadedDocument = Model.Documents.Last();
}

@using (Html.BeginForm("UploadConfirm", "SupportingEvidence", new { ApplicationId = @applicationId }, FormMethod.Post, true, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="govuk-grid-row">
        <div class="govuk-grid-column-two-thirds">
            <h1 class="govuk-heading">Check your additional supporting evidence document upload</h1>

            @{
                await Html.RenderPartialAsync("Components/UploadFileDetails",
                    new ViewDataDictionary(ViewData)
                    {
                        { "Id", uploadedDocument.DocumentId },
                        { "Name", uploadedDocument.Filename },
                        { "Size", uploadedDocument.FileSizeAsString },
});
            }

            <div class="govuk-form-group @formError">
                <fieldset class="govuk-fieldset">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
                        Is this file correct?
                    </legend>

                    @{
                        if (Model.HasError())
                        {
                            <span id="transport-upload-error" class="govuk-error-message">
                                @Model.Error
                            </span>
                        }
                    }

                    <div class="govuk-radios">
                        @{
                            foreach (var option in Model.Options)
                            {
                                <div class="govuk-radios__item">
                                    <input class="govuk-radios__input" id="@option.Id"
                                           name="option" type="radio" value="@option.Value">
                                    <label class="govuk-label govuk-radios__label" for="@option.Id">
                                        @option.Text
                                    </label>
                                </div>
                            }
                        }
                    </div>

                </fieldset>
            </div>

        </div>
    </div>

    <div class="govuk-button-group">
        @await Html.GovUkButton(new ButtonViewModel { Text = "Save and continue" })
    </div>

    @Html.Hidden("DocumentId", uploadedDocument.DocumentId, new { @id = "DocumentId" })
}

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}

ExternalPortal/Views/SupportingEvidence/WhatYouWillNeed.cshtml
@{
    ViewData["Title"] = "What you will need";

    await Html.RenderPartialAsync("Components/ViewBackLink");

    var applicationId = Context.Request.Query["ApplicationId"];
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        <h1 class="govuk-heading-l">Additional supporting evidence</h1>

        <p class="govuk-body">You'll need give us:</p>

        <ul class="govuk-list govuk-list--bullet">
            <li>any additional supporting evidence</li>
        </ul>

        <div class="govuk-button-group">
            <a href="@UrlKeys.SupportingEvidenceAdd?ApplicationId=@applicationId" class="govuk-button">Continue</a>
        </div>
    </div>
</div>

@{
    await Html.RenderPartialAsync("Components/ViewReturnToApplicationLink", applicationId);
}